task:
  skip: "changesIncludeOnly('**.md','.github/workflows/**')"
  freebsd_instance:
    matrix:
      - image_family: freebsd-13-2
      - image_family: freebsd-14-0
      - image_family: freebsd-15-0-snap

  install_script: pkg install -y meson pkgconf jansson asciidoc jq

  matrix:
    - name: BuildStatic
      static_script:
      - mkdir build_static && cd build_static
      - meson setup .. --prefix=/usr/local
      - meson configure -Dbuild_static=true -Dbuild_dynamic=false
      - ninja
      - meson test

    - name: BuildDynamic
      shared_script:
      - mkdir build_dynamic && cd build_dynamic
      - meson setup .. --prefix=/usr/local
      - meson configure -Dbuild_dynamic=true -D build_static=false
      - ninja
      - meson test
